apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: life-app
  template:
    metadata:
      labels:
        app: life-app
    spec:
      containers:
        - name: life-nginx
          image: qmarsala/life