apiVersion: v1
kind: Service
metadata:
  name: life-service
spec:
  selector:
    app: life-app
  ports:
    - protocol: "TCP"
      port: 27880
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: life-app
  template:
    metadata:
      labels:
        app: life-app
    spec:
      containers:
        - name: life-nginx
          image: qmarsala/life
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 60
